services:
    jasa_angkut_barang_app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - jasa_angkut_barang_public:/var/www/html/public:ro
        container_name: jasa_angkut_barang_app
        expose:
            - '9000'
        networks:
            - web
        restart: unless-stopped
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ['CMD-SHELL', 'pgrep php-fpm || exit 1']
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    jasa_angkut_barang_public:

networks:
    web:
        external: true
