services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - '9001:9000'
        container_name: client_1_jab_app
        volumes:
            - client_1_jab_data:/var/www/html
            - ./env.production:/var/www/html/.env:ro
        restart: unless-stopped
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ['CMD-SHELL', 'pgrep php-fpm || exit 1']
            interval: 30s
            timeout: 10s
            retries: 3
        network_mode: host

volumes:
    client_1_jab_data:
