services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: jasa_angkut_barang
        volumes:
            - appdata:/var/www/html
        restart: unless-stopped
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - postgres

    nginx:
        image: nginx:stable
        container_name: nginx
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - appdata:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    postgres:
        image: postgres:16
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '15432:5432'

volumes:
    pgdata:
    appdata:
