services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: jasa_angkut_barang
        volumes:
            - appdata:/var/www/html
        restart: unless-stopped
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
