services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: jasa_angkut_barang
        volumes:
            - ./:/var/www/html
        expose:
            - '9000' # internal FPM port
        ports:
            - '9001:9000' # host to container port mapping
        restart: unless-stopped
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ['CMD-SHELL', 'pgrep php-fpm || exit 1']
            interval: 30s
            timeout: 10s
            retries: 3
