services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - '9000:9000'
        container_name: jasa_angkut_barang
        volumes:
            - /var/www/html:/var/www/html
        restart: unless-stopped
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ['CMD-SHELL', 'pgrep php-fpm || exit 1']
            interval: 30s
            timeout: 10s
            retries: 3
