import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
    page: {
        padding: 32,
        fontSize: 10,
        fontFamily: 'Helvetica',
        backgroundColor: '#ffffff',
        color: '#333333',
    },
    header: {
        marginBottom: 24,
        borderBottom: '2px solid #2563eb',
        paddingBottom: 16,
    },
    mainTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1e40af',
        marginBottom: 4,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center',
    },
    section: {
        marginBottom: 20,
        backgroundColor: '#f8fafc',
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 20,
        borderRadius: 8,
        border: '1px solid #e2e8f0',
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 12,
        color: '#1e40af',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    infoGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 12,
    },
    infoItem: {
        flexDirection: 'column',
        gap: 4,
    },
    infoLabel: {
        fontWeight: 'bold',
        minWidth: 80,
        color: '#475569',
    },
    infoValue: {
        flex: 1,
        color: '#1e293b',
    },
    costSection: {
        marginBottom: 20,
        backgroundColor: '#ffffff',
        border: '1px solid #d1d5db',
        borderRadius: 8,
    },
    costHeader: {
        backgroundColor: '#f3f4f6',
        padding: 12,
        borderBottom: '1px solid #d1d5db',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    costHeaderText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#374151',
    },
    costBody: {
        padding: 12,
    },
    costRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 8,
        marginBottom: 2,
        borderRadius: 4,
    },
    costRowEven: {
        backgroundColor: '#f9fafb',
    },
    costRowOdd: {
        backgroundColor: '#ffffff',
    },
    costName: {
        flex: 1,
        fontSize: 10,
        color: '#374151',
    },
    costAmount: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#059669',
        minWidth: 100,
        textAlign: 'right',
    },
    costGroupSeparator: {
        marginTop: 12,
        marginBottom: 6,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
        paddingBottom: 4,
    },
    costGroupTitle: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#333',
    },
    level0: { paddingLeft: 0, fontWeight: 'bold' },
    level1: { paddingLeft: 16, fontSize: 9 },
    level2: { paddingLeft: 32, fontSize: 9, color: '#6b7280' },
    level3: { paddingLeft: 48, fontSize: 9, color: '#9ca3af' },
    summarySection: {
        backgroundColor: '#1e40af',
        padding: 16,
        borderRadius: 8,
        marginTop: 8,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 4,
    },
    summaryLabel: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#ffffff',
    },
    summaryValue: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#ffffff',
    },
    totalRow: {
        borderTop: '2px solid #3b82f6',
        paddingTop: 8,
        marginTop: 8,
    },
    totalLabel: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#fbbf24',
    },
    totalValue: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#fbbf24',
    },
    footer: {
        position: 'absolute',
        bottom: 32,
        left: 32,
        right: 32,
        textAlign: 'center',
        fontSize: 8,
        color: '#9ca3af',
        borderTop: '1px solid #e5e7eb',
        paddingTop: 8,
    },
});
